### ISSUE TITLE
Deprication of np.complex

### ISSUE THREAD

**Issue by lordmuck2020** [robinhenry/gym-anm#14]
I have just installed `gym-anm==1.1.2` on python 3.9. I used this version as there was a rendering issue on Windows that this seemed to fix (see another bug fix).

It kept throwing a deprication error saying np.complex was depricated in version 1.20. However, numpy 1.24 was intalled with this distribution (I was using a new conda env). I tried to downgrade numpy to 1.19, but this did not work.

Then I went into `\gym_anm\simulator\simulator.py` and change line 188 from:

```
        Y_bus = np.zeros((n + 1, n + 1), dtype=np.complex)
```

to 

```
        Y_bus = np.zeros((n + 1, n + 1), dtype=np.complex128)
```

The env now works fine.

Is this just me, or is this a known error?

**Comment by robinhenry** [comment]
Hey @lordmuck2020 - great catch!

This is now fixed as of: https://github.com/robinhenry/gym-anm/pull/15

I'll release a new version to `pypi` in the next couple of days.
