### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'complex'.

### ISSUE THREAD

**Issue by pablo-ta** [robinhenry/gym-anm#16]
**What**:
Deprecated call of numpy alias

**How**:
Executing the environment using the test code:
```
import gym
import time

def run():
   env = gym.make('gym_anm:ANM6Easy-v0')
   o = env.reset()

   for i in range(100):
       a = env.action_space.sample()
       o, r, done, info = env.step(a)
       env.render()
       time.sleep(0.5)  # otherwise the rendering is too fast for the human eye.

   env.close()

if __name__ == '__main__':
    run()
```

**Where**:
"gym_anm\simulator\simulator.py", line 188, in _build_admittance_matrix

` Y_bus = np.zeros((n + 1, n + 1), dtype=np.complex)`

`np.complex` was a deprecated alias for the builtin `complex`. To avoid this error in existing code, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**How to fix:**
I see two options to potencialy fix this issue:
1. Specify a requiered numpy version
2. Upgrade to numpy 1.24 and change the line code to:  
    ` Y_bus = np.zeros((n + 1, n + 1), dtype=complex)`

**Comment by robinhenry** [comment]
This was fixed in https://github.com/robinhenry/gym-anm/pull/15
and has just been released as part of `v1.1.5` - apologies about the delay!
