### ISSUE TITLE
Error closing the environment

### ISSUE THREAD

**Issue by pablo-ta** [robinhenry/gym-anm#17]
**What**:
The environment gives an error on env.close() call if env.render() has not been called because the "http_server" attribute as not been created

**How**:
Executing the environment using this modified test code:
```
import gym
import time

def run():
   env = gym.make('gym_anm:ANM6Easy-v0')
   o = env.reset()

   for i in range(100):
       a = env.action_space.sample()
       o, r, done, info = env.step(a)

   env.close()

if __name__ == '__main__':
    run()
```

**Where**:
"gym_anm\envs\anm6_env\anm6.py", line 231, in close

` rendering.close(self.http_server, self.ws_server)`

AttributeError: 'ANM6Easy' object has no attribute 'http_server'

**How to fix:**
I see two options to potencialy fix this issue:
1. Initialize the attributes "http_server" and  "ws_server" on the "__init__" function
2. check if the render has been called/initialized and only then call rendering.close.
  ```
  server_up= getattr(self, "http_server", None)
  if server_up:
          rendering.close(self.http_server, self.ws_server)
          self.render_mode = None
  ```

**Comment by robinhenry** [comment]
Thanks! This is now fixed in `v1.1.6`.

See: https://github.com/robinhenry/gym-anm/pull/19
