### ISSUE TITLE
Running speed of large-scale nodes

### ISSUE THREAD

**Issue by Kim-369** [robinhenry/gym-anm#6]
Based on gym-anm, I built my 118-node system, which had 153 devices, 92 loads and 54 units, but I found that the speed of state initialization was very slow. I'm not sure what went wrong. Could you give me some help?

**Comment by robinhenry** [comment]
Nice to hear you've decided to use `gym-anm` to simulate your system!

What do you mean exactly by "the speed of state initialization was very slow"? Could you provide a code snippet so that I can replicate your problem?

Thanks!
