### ISSUE TITLE
AttributeError: 'numpy.random._generator.Generator' object has no attribute 'randint'

### ISSUE THREAD

**Issue by sifatron** [robinhenry/gym-anm#8]
I am running into the following issue in couple of places. I am fixing it by chaging np_random to np.random and using integers instead of randint. Is that correct?

> File C:\ProgramData\Anaconda3\envs\gym-anm\lib\site-packages\gym_anm\envs\anm6_env\anm6_easy.py:31, in ANM6Easy.init_state(self)
>      27 n_dev, n_gen, n_des = 7, 2, 1
>      29 state = np.zeros(2 * n_dev + n_des + n_gen + self.K)
> ---> 31 t_0 = self.np_random.randint(0, int(24 / self.delta_t))
>      32 state[-1] = t_0
>      34 # Load (P, Q) injections.

> AttributeError: 'numpy.random._generator.Generator' object has no attribute 'randint'

Line 31 in gym-anm/gym_anm/env/anm6_env/anm6_easy.py:
```
    def init_state(self):
        n_dev, n_gen, n_des = 7, 2, 1

        state = np.zeros(2 * n_dev + n_des + n_gen + self.K)

        t_0 = self.np_random.randint(0, int(24 / self.delta_t))
        state[-1] = t_0
```

**Comment by robinhenry** [comment]
`numpy` recently deprecated the use of `np.random.Generator.randint` and replaced it with `.integers()`: https://github.com/ray-project/ray/issues/24133#issuecomment-1108369059

I just fixed it in #10 and it will be part of thte `1.1.0` release (probably later today).
