### ISSUE TITLE
Rendering Problem (Blank Screen) 

### ISSUE THREAD

**Issue by sifatron** [robinhenry/gym-anm#9]
I am running the following code:

```
import gym
import time

def run():
    env = gym.make('gym_anm:ANM6Easy-v0')
    o = env.reset()
    
    for i in range(100):
        a = env.action_space.sample()
        o, r, done, info = env.step(a)
        env.render()
        time.sleep(0.5)  # otherwise the rendering is too fast for the human eye.
    env.close()

if __name__ == '__main__':
    run()
```

I get a blank screen on my browser. Running on both Windows 10 and 11.

**Comment by robinhenry** [comment]
@sifatron  could you install the latest version with
```
pip install gym-anm==1.1.2
```
and try again?

I doubt that will fix the problem, but it's worth a try. 

I don't have access to a windows machine, so it's hard for me to troubleshoot this. Do you have any extra information about the problem? Some questions that come to mind:
- what browser does the tab open in (it should be your default browser)?
- have you tried opening it in a different browser? I'd recommend Chrome.

If that still doesn't fix it, would you be able to share the Console logs of the Chrome tab? You should be able to view them with `Shift` + `CTRL` + `J`, as explained [here](https://balsamiq.com/support/faqs/browserconsole/#google-chrome).

Thanks!
